#ifndef LAB_05_03_QUEUE_H
#define LAB_05_03_QUEUE_H

#define MAX_QUEUE_SIZE 100

enum errors
{
    QUEUE_OVERFLOW = 1,
    QUEUE_UNDERFLOW,
    NODE_ALLOC_ERROR,
    FREE_NODE_ALLOC_ERROR,
};

#endif //LAB_05_03_QUEUE_H
